import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import optimizeRouter from "./optimize";
import competitorRouter from "./competitor";
import crawlRouter from "./crawl";
import aeoRouter from "./aeo";
import deployRouter from "./deploy";
import optimizationsRouter from "./optimizations";
import agencyRouter from "./agency";
import sitemapRouter from "./sitemap";
import hreflangRouter from "./hreflang";
import contentGapsRouter from "./content-gaps";
import siteMonitorRouter from "./site-monitor";
import blogGeneratorRouter from "./blog-generator";
import blogFromKeywordRouter from "./blog-from-keyword";
import pricingRouter from "./pricing";
import paymentsRouter from "./payments";
import auditRouter from "./audit";
import intentRouter from "./intent";
import toolsRouter from "./tools";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(optimizeRouter);
router.use(competitorRouter);
router.use(crawlRouter);
router.use(aeoRouter);
router.use(deployRouter);
router.use(optimizationsRouter);
router.use(agencyRouter);
router.use(sitemapRouter);
router.use(hreflangRouter);
router.use(contentGapsRouter);
router.use(siteMonitorRouter);
router.use(blogGeneratorRouter);
router.use(blogFromKeywordRouter);
router.use(pricingRouter);
router.use(paymentsRouter);
router.use(auditRouter);
router.use(intentRouter);
router.use(toolsRouter);

export default router;
